volumes:
    logs:
      name: thpsbot_logs
    json:
      name: thpsbot_json

services:
  thpsbot:
    container_name: thpsbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app:rw
      - logs:/app/logs:rw
      - json:/app/json:rw
    networks:
      - thpsbot

networks:
  thpsbot:
    driver: bridge