volumes:
    logs:
      name: thpsbot_logs

services:
  thpsbot:
    container_name: THPSBot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app:rw
      - logs:/app/logs:rw
    networks:
      - thpsbot

networks:
  thpsbot:
    driver: bridge