from thpsbot.models.speedrun_api import (
    SRCLinks,
    SRCNewRuns,
    SRCNewRunsPagination,
    SRCPlayers,
    SRCRuns,
    SRCStatus,
    SRCSystem,
    SRCTimes,
    SRCVideos,
    SRCVideosLinks,
)
from thpsbot.models.thpsrun_api import (
    THPSRunCategory,
    THPSRunGame,
    THPSRunLevel,
    THPSRunMeta,
    THPSRunNewRuns,
    THPSRunPBs,
    THPSRunPlayerAwards,
    THPSRunPlayers,
    THPSRunPlayerStats,
    THPSRunRuns,
    THPSRunStatus,
    THPSRunSystem,
    THPSRunSystemPlatform,
    THPSRunTimes,
    THPSRunVariable,
    THPSRunVariableValue,
    THPSRunVideos,
)

__all__ = [
    # THPS.RUN API
    "THPSRunGame",
    "THPSRunCategory",
    "THPSRunLevel",
    "THPSRunPlayers",
    "THPSRunSystem",
    "THPSRunRuns",
    "THPSRunMeta",
    "THPSRunPBs",
    "THPSRunPlayerAwards",
    "THPSRunPlayerStats",
    "THPSRunStatus",
    "THPSRunSystemPlatform",
    "THPSRunTimes",
    "THPSRunVideos",
    "THPSRunVariable",
    "THPSRunVariableValue",
    "THPSRunNewRuns",
    # SPEEDRUN.COM API
    "SRCLinks",
    "SRCPlayers",
    "SRCStatus",
    "SRCSystem",
    "SRCTimes",
    "SRCVideos",
    "SRCVideosLinks",
    "SRCRuns",
    "SRCNewRuns",
    "SRCNewRunsPagination",
]
